### ISSUE TITLE
.catch()

### ISSUE THREAD

**Issue by remexre** [augustoroman/promise#1]
Could a `.catch()` function be added? In browser promises, for example, you can do:

``` javascript
Promise.reject("asdf")
    .catch(err => console.error(err));
```

Which is equivalent to:

``` javascript
Promise.reject("asdf")
    .then(id => id, err => console.error(err));
```

**Comment by augustoroman** [comment]
I was trying to adhere to the [Promises/A+ spec](https://promisesaplus.com/), which doesn't support the `.catch()` convenience method.   I was doing this to avoid going down the rabbit hole of supporting everything that [when](https://github.com/cujojs/when), [bluebird](http://bluebirdjs.com/), or other libs support.  I recommend that if you need fancier promises, use one of those libs to wrap these promises (e.g. [when()](https://github.com/cujojs/when/blob/master/docs/api.md#when), or [bluebird's Promise.resolve()](http://bluebirdjs.com/docs/api/promise.resolve.html))
